apiVersion: v1
kind: Namespace
metadata:
  name: ozet

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOnsidXNlcm5hbWUiOiJiYXJ0a2ltMDcxMjAiLCJwYXNzd29yZCI6IldvZ2hrczA3MTIiLCJlbWFpbCI6ImphZWh3YW5raW0wNzEyMEBnbWFpbC5jb20iLCJhdXRoIjoiWW1GeWRHdHBiVEEzTVRJd09sZHZaMmhyY3pBM01UST0ifX19
kind: Secret
metadata:
  creationTimestamp: "2021-08-14T16:52:07Z"
  name: regcred
  namespace: ozet
  resourceVersion: "9943"
  uid: 80838d71-e6f2-4a7d-b426-4b47081c1368
type: kubernetes.io/dockerconfigjson:wq:wq!

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ozet-core-api
  name: ozet-core-api-deployment
  namespace: ozet
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ozet-core-api
  template:
    metadata:
      labels:
        app: ozet-core-api
    spec:
      containers:
      - name: ozet-core-api
        image: bartkim07120/ozet-core-api:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ozet-core-api
  name: ozet-core-api-service
  namespace: ozet
spec:
  selector:
    app: ozet-core-api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
